"""Pydantic validation models for external API responses.

These models validate data coming FROM external services (Gemini, edge-tts)
before it enters the pipeline state. They are NOT the LangGraph state —
see state.py for that.
"""

from typing import Literal

from pydantic import BaseModel, Field, field_validator


# ---------------------------------------------------------------------------
# Config validation (loaded at startup from config.yaml)
# ---------------------------------------------------------------------------


class CharacterConfig(BaseModel):
    """A character entry from config.yaml, validated at startup."""

    name: str = Field(
        ..., min_length=1, description="Character display name"
    )
    show: str = Field(
        ..., min_length=1, description="Source show/franchise name"
    )
    role: Literal["confused", "explainer"] = Field(
        ..., description="Character role in dialogue"
    )
    voice: str = Field(
        ...,
        min_length=1,
        description="edge-tts voice ID (e.g. en-US-GuyNeural)",
    )
    image_folder: str = Field(
        ...,
        min_length=1,
        description="Folder name under assets/characters/",
    )


# ---------------------------------------------------------------------------
# Gemini script writer output
# ---------------------------------------------------------------------------


class ScriptLine(BaseModel):
    """A single dialogue line from the Gemini-generated script."""

    character: str = Field(
        ..., min_length=1, description="Character name speaking this line"
    )
    line: str = Field(
        ..., min_length=1, description="The dialogue text to be spoken"
    )

    @field_validator("character", "line")
    @classmethod
    def strip_whitespace(cls, v: str) -> str:
        """Strip leading/trailing whitespace from string fields."""
        return v.strip()


# ---------------------------------------------------------------------------
# edge-tts word-boundary timestamps
# ---------------------------------------------------------------------------


class WordTimestamp(BaseModel):
    """A single word with its timing offset from edge-tts word boundaries."""

    word: str = Field(..., description="The spoken word")
    offset_ms: float = Field(
        ..., ge=0, description="Start time offset in milliseconds"
    )
    duration_ms: float = Field(
        ..., ge=0, description="Duration of the word in milliseconds"
    )


class AudioSegment(BaseModel):
    """One audio file generated by edge-tts for a single script line."""

    path: str = Field(..., description="Absolute path to the WAV file")
    duration_ms: float = Field(
        ..., gt=0, description="Total duration in milliseconds"
    )
    character: str = Field(
        ..., description="Character who speaks this line"
    )
    line_index: int = Field(
        ..., ge=0, description="Index of this line in the script"
    )
    word_timestamps: list[WordTimestamp] = Field(
        default_factory=list,
        description="Word-level timing data from edge-tts",
    )


# ---------------------------------------------------------------------------
# Gemini metadata generator output
# ---------------------------------------------------------------------------


class VideoMetadata(BaseModel):
    """YouTube Shorts metadata generated by Gemini."""

    title: str = Field(
        ...,
        min_length=1,
        max_length=100,
        description="Video title (target: under 60 chars with emojis)",
    )
    description: str = Field(
        ...,
        min_length=1,
        description="2-3 sentence video description",
    )
    hashtags: list[str] = Field(
        ...,
        min_length=1,
        description="List of hashtags including #Shorts",
    )

    @field_validator("hashtags")
    @classmethod
    def ensure_shorts_hashtag(cls, v: list[str]) -> list[str]:
        """Guarantee #Shorts is always present in hashtags."""
        normalized = [tag if tag.startswith("#") else f"#{tag}" for tag in v]
        if "#Shorts" not in normalized:
            normalized.append("#Shorts")
        return normalized


# ---------------------------------------------------------------------------
# Queue entry (written to queue.json)
# ---------------------------------------------------------------------------


class QueueEntry(BaseModel):
    """A single entry in queue.json representing a video ready for upload."""

    queue_entry_id: str = Field(
        ..., description="Unique ID for this queue entry (UUID4)"
    )
    run_id: str = Field(
        ..., description="Pipeline run ID that created this entry"
    )
    video_path: str = Field(
        ..., description="Absolute path to the final .mp4 file"
    )
    title: str
    description: str
    hashtags: list[str]
    tags: list[str] = Field(default_factory=list)
    scheduled_upload_time: str = Field(
        ..., description="ISO 8601 datetime for scheduled upload"
    )
    status: str = Field(
        default="pending",
        pattern=r"^(pending|uploaded|failed)$",
        description="Upload status: pending | uploaded | failed",
    )
    youtube_video_id: str | None = Field(
        default=None,
        description="YouTube video ID after successful upload",
    )
    uploaded_at: str | None = Field(
        default=None,
        description="ISO 8601 datetime when upload completed",
    )
    error_message: str | None = Field(
        default=None,
        description="Error message if upload failed",
    )
    created_at: str = Field(
        ..., description="ISO 8601 datetime when entry was created"
    )
